// ~/lib/defaultPageContent.ts
import { CraftJson } from "~/constants/types/models";

export const DEFAULT_PAGE_CONTENT: Record<string, CraftJson> = {
  home: {
    ROOT: {
      parent: "",
      type: { resolvedName: "RootContainer" },
      isCanvas: true,
      props: { id: "root" },
      displayName: "Page",
      custom: {},
      hidden: false,
      nodes: [
        "navbar",
        "3B6BNq-u_X",
        "JRei7uceo9",
        "-AXrhlnGV6",
        "ad-001",
        "6Vw5-UMpNM",
        "d_BgX9iPNs",
        "TvGnWJrhJP",
        "footer-001",
      ],
      linkedNodes: {},
    },

    navbar: {
      type: { resolvedName: "NavbarBlock" },
      isCanvas: false,
      props: {},
      displayName: "Navbar",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
      },

    "3B6BNq-u_X": {
      type: { resolvedName: "HeroBanner" },
      isCanvas: false,
      props: {
        title: "Welcome to Our Store",
        subtitle: "Discover our curated collection of amazing products.",
        ctaLabel: "Shop Now",
        ctaUrl: "#",
        backgroundColor: "#111827",
        textColor: "#ffffff",
        minHeight: 480,
        alignment: "center",
      },
      displayName: "HeroBanner",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    JRei7uceo9: {
      type: { resolvedName: "CategoryBlock" },
      isCanvas: false,
      props: { title: "Top Categories" },
      displayName: "CategoryBlock",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "-AXrhlnGV6": {
      type: { resolvedName: "ProductGrid" },
      isCanvas: false,
      props: {
        columns: 3,
        showPrices: true,
        showAddToCart: true,
        sectionTitle: "Top Products",
        showTitle: true,
        cardBackground: "#ffffff",
        accentColor: "#111827",
      },
      displayName: "ProductGrid",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },

        "ad-001": {
      type: { resolvedName: "AdBannerBlock" },
      isCanvas: false,
      props: {
        text: "Ad Space",
        backgroundColor: "#fb923c",
        textColor: "#ffffff",
        height: 240,
      },
      displayName: "AdBanner",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },


    "6Vw5-UMpNM": {
      type: { resolvedName: "ProductGrid" },
      isCanvas: false,
      props: {
        columns: 3,
        showPrices: true,
        showAddToCart: true,
        sectionTitle: "New Arrivals",
        showTitle: true,
        cardBackground: "#ffffff",
        accentColor: "#111827",
      },
      displayName: "ProductGrid",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    d_BgX9iPNs: {
      type: { resolvedName: "ProductGrid" },
      isCanvas: false,
      props: {
        columns: 3,
        showPrices: true,
        showAddToCart: true,
        sectionTitle: "Hot Deals",
        showTitle: true,
        cardBackground: "#ffffff",
        accentColor: "#111827",
      },
      displayName: "ProductGrid",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    TvGnWJrhJP: {
      type: { resolvedName: "StoreLocationBlock" },
      isCanvas: false,
      props: { title: "Our Locations" },
      displayName: "StoreLocationBlock",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "footer-001": {
      type: { resolvedName: "FooterBlock" },
      isCanvas: false,
      props: {},
      displayName: "Footer",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
  },
  products: {
    ROOT: {
      parent: "",
      type: { resolvedName: "RootContainer" },
      isCanvas: true,
      props: { id: "root" },
      displayName: "Page",
      custom: {},
      hidden: false,
      nodes: [
        "navbar-products",
        "annbar-products",
        "products-hero-001",
        "catalog-products-001",
        "footer-products",
      ],
      linkedNodes: {},
    },
    "navbar-products": {
      type: { resolvedName: "NavbarBlock" },
      isCanvas: false,
      props: {},
      displayName: "Navbar",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "annbar-products": {
      type: { resolvedName: "AnnouncementBar" },
      isCanvas: false,
      props: {
        text: "New Season Drop — Fresh styles just landed. Shop before they sell out!",
        backgroundColor: "#111827",
        textColor: "#ffffff",
        linkLabel: "Shop Now",
      },
      displayName: "AnnouncementBar",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "products-hero-001": {
      type: { resolvedName: "ProductsHeroBlock" },
      isCanvas: false,
      props: {
        eyebrow: "New Season",
        heading: "Curated Selection",
        subheading: "The Full Inventory",
        activePillBg: "#111827",
        activePillText: "#ffffff",
      },
      displayName: "ProductsHeroBlock",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "catalog-products-001": {
      type: { resolvedName: "ProductCatalogBlock" },
      isCanvas: false,
      props: {
        currencySymbol: "₦",
        accentColor: "#B3561B",
        cardBackground: "#ffffff",
        showPrices: true,
        showAddToCart: true,
        showSizeFilter: true,
        showPriceFilter: true,
        showSortBy: true,
      },
      displayName: "ProductCatalogBlock",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "footer-products": {
      type: { resolvedName: "FooterBlock" },
      isCanvas: false,
      props: {},
      displayName: "Footer",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
  },

  product: {
    ROOT: {
      parent: "",
      type: { resolvedName: "RootContainer" },
      isCanvas: true,
      props: { id: "root" },
      displayName: "Page",
      custom: {},
      hidden: false,
      nodes: ["navbar-product", "product-details-001", "footer-product"],
      linkedNodes: {},
    },
    "navbar-product": {
      type: { resolvedName: "NavbarBlock" },
      isCanvas: false,
      props: {},
      displayName: "Navbar",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "product-details-001": {
      type: { resolvedName: "ProductDetails" },
      isCanvas: false,
      props: {
        productName: 'Premium Wireless Headphones',
        category: 'ELECTRONICS',
        price: '₦12,500',
        originalPrice: '₦15,000',
        description: 'Experience exceptional sound quality with our premium wireless headphones.',
        showReviews: true,
        showRelated: true,
        accentColor: '#B3561B',
      },
      displayName: "ProductDetails",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "footer-product": {
      type: { resolvedName: "FooterBlock" },
      isCanvas: false,
      props: {},
      displayName: "Footer",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
  },

  locations: {
    ROOT: {
      parent: "",
      type: { resolvedName: "RootContainer" },
      isCanvas: true,
      props: { id: "root" },
      displayName: "Page",
      custom: {},
      hidden: false,
      nodes: [
        "navbar-locations",
        "annbar-locations",
        "location-block-001",
        "footer-locations",
      ],
      linkedNodes: {},
    },
    "navbar-locations": {
      type: { resolvedName: "NavbarBlock" },
      isCanvas: false,
      props: {},
      displayName: "Navbar",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "annbar-locations": {
      type: { resolvedName: "AnnouncementBar" },
      isCanvas: false,
      props: {
        text: "Visit any of our branches across the city — we're open and ready to serve you!",
        backgroundColor: "#f59e0b",
        textColor: "#000000",
        linkLabel: "",
      },
      displayName: "AnnouncementBar",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "location-block-001": {
      type: { resolvedName: "LocationBlock" },
      isCanvas: false,
      props: { title: "Our Locations" },
      displayName: "LocationBlock",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "footer-locations": {
      type: { resolvedName: "FooterBlock" },
      isCanvas: false,
      props: {},
      displayName: "Footer",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
  },
  cart: {
    ROOT: {
      parent: "",
      type: { resolvedName: "RootContainer" },
      isCanvas: true,
      props: { id: "root" },
      displayName: "Page",
      custom: {},
      hidden: false,
      nodes: ["navbar-cart", "cart-block-001", "footer-cart"],
      linkedNodes: {},
    },
    "navbar-cart": {
      type: { resolvedName: "NavbarBlock" },
      isCanvas: false,
      props: {},
      displayName: "Navbar",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "cart-block-001": {
      type: { resolvedName: "CartSummary" },
      isCanvas: false,
      props: { accentColor: "#B3561B", currencySymbol: "₦" },
      displayName: "CartSummary",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "footer-cart": {
      type: { resolvedName: "FooterBlock" },
      isCanvas: false,
      props: {},
      displayName: "Footer",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
  },
  checkout: {
    ROOT: {
      parent: "",
      type: { resolvedName: "RootContainer" },
      isCanvas: true,
      props: { id: "root" },
      displayName: "Page",
      custom: {},
      hidden: false,
      nodes: ["navbar-checkout", "checkout-block-001", "footer-checkout"],
      linkedNodes: {},
    },
    "navbar-checkout": {
      type: { resolvedName: "NavbarBlock" },
      isCanvas: false,
      props: {},
      displayName: "Navbar",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "checkout-block-001": {
      type: { resolvedName: "CheckoutForm" },
      isCanvas: false,
      props: { accentColor: "#B3561B", currencySymbol: "₦" },
      displayName: "CheckoutForm",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
    "footer-checkout": {
      type: { resolvedName: "FooterBlock" },
      isCanvas: false,
      props: {},
      displayName: "Footer",
      custom: {},
      parent: "ROOT",
      hidden: false,
      nodes: [],
      linkedNodes: {},
    },
  },

};